
#PASTOR: Code generated by XML::Pastor/0.54 at 'Sat Jul 12 15:24:21 2008'

use utf8;
use strict;

use XML::Pastor;



#================================================================

package MathWorks::componentDepList;

use MathWorks::Type::componentDepList;

our @ISA=qw(MathWorks::Type::componentDepList XML::Pastor::Element);

MathWorks::componentDepList->XmlSchemaElement( bless( {
                 'baseClasses' => [
                                    'MathWorks::Type::componentDepList',
                                    'XML::Pastor::Element'
                                  ],
                 'class' => 'MathWorks::componentDepList',
                 'isRedefinable' => 1,
                 'name' => 'componentDepList',
                 'scope' => 'global',
                 'type' => 'componentDepList'
               }, 'XML::Pastor::Schema::Element' ) );

1;
