
#PASTOR: Code generated by XML::Pastor/0.54 at 'Sat Jul 12 15:24:21 2008'

use utf8;
use strict;

use XML::Pastor;



#================================================================

package MathWorks::componentDepItem;

use MathWorks::Type::componentDepItem;

our @ISA=qw(MathWorks::Type::componentDepItem XML::Pastor::Element);

MathWorks::componentDepItem->XmlSchemaElement( bless( {
                 'baseClasses' => [
                                    'MathWorks::Type::componentDepItem',
                                    'XML::Pastor::Element'
                                  ],
                 'class' => 'MathWorks::componentDepItem',
                 'isRedefinable' => 1,
                 'name' => 'componentDepItem',
                 'scope' => 'global',
                 'type' => 'componentDepItem'
               }, 'XML::Pastor::Schema::Element' ) );

1;
