
#PASTOR: Code generated by XML::Pastor/0.54 at 'Sat Jul 12 15:24:21 2008'

use utf8;
use strict;

use XML::Pastor;



#================================================================

package MathWorks::platformList;

use MathWorks::Type::platformList;

our @ISA=qw(MathWorks::Type::platformList XML::Pastor::Element);

MathWorks::platformList->XmlSchemaElement( bless( {
                 'baseClasses' => [
                                    'MathWorks::Type::platformList',
                                    'XML::Pastor::Element'
                                  ],
                 'class' => 'MathWorks::platformList',
                 'isRedefinable' => 1,
                 'name' => 'platformList',
                 'scope' => 'global',
                 'type' => 'platformList'
               }, 'XML::Pastor::Schema::Element' ) );

1;
