
#PASTOR: Code generated by XML::Pastor/0.54 at 'Sat Jul 12 15:24:21 2008'

use utf8;
use strict;

use XML::Pastor;



#================================================================

package MathWorks::productDepList;

use MathWorks::Type::productDepList;

our @ISA=qw(MathWorks::Type::productDepList XML::Pastor::Element);

MathWorks::productDepList->XmlSchemaElement( bless( {
                 'baseClasses' => [
                                    'MathWorks::Type::productDepList',
                                    'XML::Pastor::Element'
                                  ],
                 'class' => 'MathWorks::productDepList',
                 'isRedefinable' => 1,
                 'name' => 'productDepList',
                 'scope' => 'global',
                 'type' => 'productDepList'
               }, 'XML::Pastor::Schema::Element' ) );

1;
