
#PASTOR: Code generated by XML::Pastor/0.54 at 'Sat Jul 12 15:24:21 2008'

use utf8;
use strict;

use XML::Pastor;



#================================================================

package MathWorks::product;

use MathWorks::Type::product;

our @ISA=qw(MathWorks::Type::product XML::Pastor::Element);

MathWorks::product->XmlSchemaElement( bless( {
                 'baseClasses' => [
                                    'MathWorks::Type::product',
                                    'XML::Pastor::Element'
                                  ],
                 'class' => 'MathWorks::product',
                 'isRedefinable' => 1,
                 'name' => 'product',
                 'scope' => 'global',
                 'type' => 'product'
               }, 'XML::Pastor::Schema::Element' ) );

1;
