
#PASTOR: Code generated by XML::Pastor/0.54 at 'Sat Jul 12 15:24:21 2008'

use utf8;
use strict;

use XML::Pastor;



#================================================================

package MathWorks::Type::ownerInfo;


our @ISA=qw(XML::Pastor::ComplexType);

MathWorks::Type::ownerInfo->mk_accessors( qw(owningTeam contactName));

MathWorks::Type::ownerInfo->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'MathWorks::Type::ownerInfo',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'contactName' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'name' => 'contactName',
                                                          'scope' => 'local',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'owningTeam' => bless( {
                                                         'class' => 'XML::Pastor::Builtin::string',
                                                         'name' => 'owningTeam',
                                                         'scope' => 'local',
                                                         'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                       }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'owningTeam',
                                 'contactName'
                               ],
                 'isRedefinable' => 1,
                 'name' => 'ownerInfo',
                 'scope' => 'global'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;
