
#PASTOR: Code generated by XML::Pastor/0.54 at 'Sat Jul 12 15:24:21 2008'

use utf8;
use strict;

use XML::Pastor;



#================================================================

package MathWorks::Type::platformList;


our @ISA=qw(XML::Pastor::ComplexType);

MathWorks::Type::platformList->mk_accessors( qw(platform));

MathWorks::Type::platformList->XmlSchemaType( bless( {
                 'attributeInfo' => {},
                 'attributePrefix' => '_',
                 'attributes' => [],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'MathWorks::Type::platformList',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'platform' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::string',
                                                       'maxOccurs' => 'unbounded',
                                                       'name' => 'platform',
                                                       'scope' => 'local',
                                                       'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'platform'
                               ],
                 'isRedefinable' => 1,
                 'name' => 'platformList',
                 'scope' => 'global'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;
