
#PASTOR: Code generated by XML::Pastor/0.54 at 'Sat Jul 12 15:24:21 2008'

use utf8;
use strict;

use XML::Pastor;



#================================================================

package MathWorks::Type::product;

use MathWorks::Type::componentDepList;
use MathWorks::Type::ownerInfo;
use MathWorks::Type::platformList;
use MathWorks::Type::productDepList;

our @ISA=qw(XML::Pastor::ComplexType);

MathWorks::Type::product->mk_accessors( qw(_name owner productName productVersion licenseName externalProductIdentifier released releasePlatforms dependsOn requiredProducts recommendedProducts));

# Attribute accessor aliases

sub name { &_name; }

MathWorks::Type::product->XmlSchemaType( bless( {
                 'attributeInfo' => {
                                    'name' => bless( {
                                                     'class' => 'XML::Pastor::Builtin::string',
                                                     'name' => 'name',
                                                     'scope' => 'local',
                                                     'type' => 'string|http://www.w3.org/2001/XMLSchema',
                                                     'use' => 'required'
                                                   }, 'XML::Pastor::Schema::Attribute' )
                                  },
                 'attributePrefix' => '_',
                 'attributes' => [
                                   'name'
                                 ],
                 'baseClasses' => [
                                    'XML::Pastor::ComplexType'
                                  ],
                 'class' => 'MathWorks::Type::product',
                 'contentType' => 'complex',
                 'elementInfo' => {
                                  'dependsOn' => bless( {
                                                        'class' => 'MathWorks::Type::componentDepList',
                                                        'minOccurs' => '0',
                                                        'name' => 'dependsOn',
                                                        'scope' => 'local',
                                                        'type' => 'componentDepList'
                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'externalProductIdentifier' => bless( {
                                                                        'class' => 'XML::Pastor::Builtin::nonNegativeInteger',
                                                                        'name' => 'externalProductIdentifier',
                                                                        'scope' => 'local',
                                                                        'type' => 'nonNegativeInteger|http://www.w3.org/2001/XMLSchema'
                                                                      }, 'XML::Pastor::Schema::Element' ),
                                  'licenseName' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'name' => 'licenseName',
                                                          'scope' => 'local',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'owner' => bless( {
                                                    'class' => 'MathWorks::Type::ownerInfo',
                                                    'minOccurs' => '0',
                                                    'name' => 'owner',
                                                    'scope' => 'local',
                                                    'type' => 'ownerInfo'
                                                  }, 'XML::Pastor::Schema::Element' ),
                                  'productName' => bless( {
                                                          'class' => 'XML::Pastor::Builtin::string',
                                                          'name' => 'productName',
                                                          'scope' => 'local',
                                                          'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                        }, 'XML::Pastor::Schema::Element' ),
                                  'productVersion' => bless( {
                                                             'class' => 'XML::Pastor::Builtin::string',
                                                             'name' => 'productVersion',
                                                             'scope' => 'local',
                                                             'type' => 'string|http://www.w3.org/2001/XMLSchema'
                                                           }, 'XML::Pastor::Schema::Element' ),
                                  'recommendedProducts' => bless( {
                                                                  'class' => 'MathWorks::Type::productDepList',
                                                                  'minOccurs' => '0',
                                                                  'name' => 'recommendedProducts',
                                                                  'scope' => 'local',
                                                                  'type' => 'productDepList'
                                                                }, 'XML::Pastor::Schema::Element' ),
                                  'releasePlatforms' => bless( {
                                                               'class' => 'MathWorks::Type::platformList',
                                                               'name' => 'releasePlatforms',
                                                               'scope' => 'local',
                                                               'type' => 'platformList'
                                                             }, 'XML::Pastor::Schema::Element' ),
                                  'released' => bless( {
                                                       'class' => 'XML::Pastor::Builtin::boolean',
                                                       'default' => 'true',
                                                       'name' => 'released',
                                                       'scope' => 'local',
                                                       'type' => 'boolean|http://www.w3.org/2001/XMLSchema'
                                                     }, 'XML::Pastor::Schema::Element' ),
                                  'requiredProducts' => bless( {
                                                               'class' => 'MathWorks::Type::productDepList',
                                                               'minOccurs' => '0',
                                                               'name' => 'requiredProducts',
                                                               'scope' => 'local',
                                                               'type' => 'productDepList'
                                                             }, 'XML::Pastor::Schema::Element' )
                                },
                 'elements' => [
                                 'owner',
                                 'productName',
                                 'productVersion',
                                 'licenseName',
                                 'externalProductIdentifier',
                                 'released',
                                 'releasePlatforms',
                                 'dependsOn',
                                 'requiredProducts',
                                 'recommendedProducts'
                               ],
                 'isRedefinable' => 1,
                 'name' => 'product',
                 'scope' => 'global'
               }, 'XML::Pastor::Schema::ComplexType' ) );

1;
